name: Build Docs
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install requirements_docs.txt
      run: pip install -r requirements_docs.txt
    - name: Install and Build 🔧
      working-directory: ./docs
      run: |
        make html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./docs/_build/html # The folder the action should deploy.
